# Generated by Django 2.2.1 on 2019-06-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190602_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
